package com.example.morsecodeconverter.model

object AlphabetModel {
    const val A = "·–"
    const val B = "–···"
    const val C = "–·–·"
    const val D = "–··"
    const val E = "·"
    const val F = "··–·"
    const val G = "––·"
    const val H = "····"
    const val I = "··"
    const val J = "·–––"
    const val K = "–·–"
    const val L = "·–··"
    const val M = "––"
    const val N = "–·"
    const val O = "–––"
    const val P = "·––·"
    const val Q = " ––·–"
    const val R = "·–·"
    const val S = "···"
    const val T = "–"
    const val U = "··–"
    const val V = "···–"
    const val W = "·––"
    const val X = "–··–"
    const val Y = "–·––"
    const val Z = "––··"
}